## Librerias

In [47]:
try:
    import pandas as pd
except ImportError:
    print("Pandas not installed")
    %pip install pandas --user

try:
    import matplotlib.pyplot as plt
except ImportError:
    print("Matplotlib not installed")
    %pip install matplotlib --user

import ssl

ssl._create_default_https_context = ssl._create_unverified_context

In [48]:
import pandas as pd
import matplotlib.pyplot as plt

## Lectura de datos

- [Dataset Qatar 2022: https://www.kaggle.com/datasets/shrikrishnaparab/fifa-world-cup-2022-qatar-match-data](https://www.kaggle.com/datasets/shrikrishnaparab/fifa-world-cup-2022-qatar-match-data)

In [49]:
archivo = "https://raw.githubusercontent.com/IgnacioPardo/Tecnologias_Exponenciales_2025/refs/heads/main/qatar.csv"

# Leer datos del archivo
mundial : pd.DataFrame = pd.read_csv(archivo)
mundial

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
0,1,Sun,20-Nov-22,17:00,Al Bayt Stadium,Daniele Orsato,Group A,QATAR,ECUADOR,67372,...,0,1,6,5,0,0,52,72,256,279
1,2,Mon,21-Nov-22,14:00,Khalifa International Stadium,Raphael Claus,Group B,ENGLAND,IRAN,45334,...,0,1,8,13,0,0,63,72,139,416
2,3,Mon,21-Nov-22,17:00,Al Thumama Stadium,Wilton Sampaio,Group A,SENEGAL,NETHERLANDS,41721,...,0,0,9,15,0,0,63,73,263,251
3,4,Mon,21-Nov-22,20:00,Ahmed bin Ali Stadium,Abdulrahman Ibrahim Al Jassim,Group B,UNITED STATES,WALES,43418,...,0,1,7,7,0,0,81,72,242,292
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,60,Sat,10-Dec-22,20:00,Al Bayt Stadium,Wilton Sampaio,Quarter-final,ENGLAND,FRANCE,68895,...,1,0,9,15,0,0,49,54,193,308
60,61,Tue,13-Dec-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Semi-Final,ARGENTINA,CROATIA,88966,...,1,0,12,10,0,0,85,63,321,260
61,62,Wed,14-Dec-22,20:00,Al Bayt Stadium,Cesar Ramos,Semi-Final,FRANCE,MOROCCO,68294,...,0,0,13,14,0,0,72,47,328,218
62,63,Sat,17-Dec-22,16:00,Khalifa International Stadium,Abdulrahman Ibrahim Al Jassim,Play-off for third place,CROATIA,MOROCCO,44137,...,0,0,7,14,0,0,75,72,288,277
63,64,Sun,18-Dec-22,16:00,Lusail Iconic Stadium,Szymon Marciniak,Final,ARGENTINA,FRANCE,88966,...,1,2,11,21,0,0,87,104,280,409

In [14]:
# Cuantos partidos se jugaron?
# Completar
len(mundial)

64

In [21]:
# Que datos tiene el dataset? (Pista: usar .info(), .describe(), .columns, .head())
# Checkear columnas
# Completar
mundial.info()
mundial.describe()
mundial.columns
mundial.head()

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 59 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   match_no                         64 non-null     int64
 1   day_of_week                      64 non-null     str
 2   date                             64 non-null     str
 3   hour                             64 non-null     str
 4   venue                            64 non-null     str
 5   referee                          64 non-null     str
 6   group                            64 non-null     str
 7   1                                64 non-null     str
 8   2                                64 non-null     str
 9   attendance                       64 non-null     int64
 10  1_xg                             64 non-null     float64
 11  2_xg                             64 non-null     float64
 12  1_poss                           64 non-null     int64
 13  2_poss                           64 non-null     int64
 14  1_goals                          64 non-null     int64
 15  2_goals                          64 non-null     int64
 16  score                            64 non-null     str
 17  1_attempts                       64 non-null     int64
 18  2_attempts                       64 non-null     int64
 19  1_conceded                       64 non-null     int64
 20  2_conceded                       64 non-null     int64
 21  1_goal_inside_penalty_area       64 non-null     int64
 22  2_goal_inside_penalty_area       64 non-null     int64
 23  1_goal_outside_penalty_area      64 non-null     int64
 24  2_goal_outside_penalty_area      64 non-null     int64
 25  1_ontarget                       64 non-null     int64
 26  2_ontarget                       64 non-null     int64
 27  1_offtarget                      64 non-null     int64
 28  2_offtarget                      64 non-null     int64
 29  1_attempts_inside_penalty_area   64 non-null     int64
 30  2_attempts_inside_penalty_area   64 non-null     int64
 31  1_attempts_outside_penalty_area  64 non-null     int64
 32  2_attempts_outside_penalty_area  64 non-null     int64
 33  1_yellow_cards                   64 non-null     int64
 34  2_yellow_cards                   64 non-null     int64
 35  1_red_cards                      64 non-null     int64
 36  2_red_cards                      64 non-null     int64
 37  faul_against_1                   64 non-null     int64
 38  faul_against_2                   64 non-null     int64
 39  1_offsides                       64 non-null     int64
 40  2_offsides                       64 non-null     int64
 41  1_passes                         64 non-null     int64
 42  2_passes                         64 non-null     int64
 43  1_passes_compeletd               64 non-null     int64
 44  2_passes_compeletd               64 non-null     int64
 45  1_corners                        64 non-null     int64
 46  2_corners                        64 non-null     int64
 47  1_free_kicks                     64 non-null     int64
 48  2_free_kicks                     64 non-null     int64
 49  1_panelties_scored               64 non-null     int64
 50  2_panelties_scored               64 non-null     int64
 51  1_goal_prevented                 64 non-null     int64
 52  2_goal_prevented                 64 non-null     int64
 53  1_own_goal                       64 non-null     int64
 54  2_own_goal                       64 non-null     int64
 55  1_forced_turnovers               64 non-null     int64
 56  2_forced_turnovers               64 non-null     int64
 57  1_defensive_pressure_applied     64 non-null     int64
 58  2_defensive_pressure_applied     64 non-null     int64
dtypes: float64(2), int64(48), str(9)
memory usage: 29.6 KB

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
0,1,Sun,20-Nov-22,17:00,Al Bayt Stadium,Daniele Orsato,Group A,QATAR,ECUADOR,67372,...,0,1,6,5,0,0,52,72,256,279
1,2,Mon,21-Nov-22,14:00,Khalifa International Stadium,Raphael Claus,Group B,ENGLAND,IRAN,45334,...,0,1,8,13,0,0,63,72,139,416
2,3,Mon,21-Nov-22,17:00,Al Thumama Stadium,Wilton Sampaio,Group A,SENEGAL,NETHERLANDS,41721,...,0,0,9,15,0,0,63,73,263,251
3,4,Mon,21-Nov-22,20:00,Ahmed bin Ali Stadium,Abdulrahman Ibrahim Al Jassim,Group B,UNITED STATES,WALES,43418,...,0,1,7,7,0,0,81,72,242,292
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361

## Analisis

### Primera Parte

In [22]:
# Cuantas selecciones participaron?
# Completar
selecciones = pd.concat([mundial["1"], mundial["2"]]).unique()
selecciones

<StringArray>
[         'QATAR',        'ENGLAND',        'SENEGAL',  'UNITED STATES',
      'ARGENTINA',        'DENMARK',         'MEXICO',         'FRANCE',
        'MOROCCO',        'GERMANY',          'SPAIN',        'BELGIUM',
    'SWITZERLAND',        'URUGUAY',       'PORTUGAL',         'BRAZIL',
          'WALES',    'NETHERLANDS',        'TUNISIA',         'POLAND',
          'JAPAN',        'CROATIA',       'CAMEROON', 'KOREA REPUBLIC',
        'ECUADOR',           'IRAN',      'AUSTRALIA',   'SAUDI ARABIA',
         'CANADA',     'COSTA RICA',          'GHANA',         'SERBIA']
Length: 32, dtype: str

In [23]:
# Cuantas fases tiene el mundial?
# Completar
fases = mundial["group"].apply(lambda g: "Group Stage" if g.startswith("Group") else g).unique()
print(fases)
len(fases)

<StringArray>
[             'Group Stage',              'Round of 16',
            'Quarter-final',               'Semi-Final',
 'Play-off for third place',                    'Final']
Length: 6, dtype: str

6

In [18]:
# Cual fue la "attendance" promedio por partido?
# Completar
promedio = mundial["attendance"].mean()
print(f"Attendance promedio por partido: {promedio:,.0f} personas")

Attendance promedio por partido: 53,191 personas

In [28]:
# Cual fue el partido con mas diferencia de goles?
# Completar
mundial["diferencia_goles"] = (mundial["1_goals"] - mundial["2_goals"])
Mayor_Diferencia = mundial["diferencia_goles"].max()
Partido_Mayor_Diferencia = mundial[mundial["diferencia_goles"] == Mayor_Diferencia]
Partido_Mayor_Diferencia

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied,diferencia_goles
10,11,Wed,23-Nov-22,17:00,Al Thumama Stadium,Mohammed Abdulla Hassan,Group E,SPAIN,COSTA RICA,40013,...,0,0,17,0,0,46,76,185,585,7

In [ ]:
#Cual es la selección que mas penales metió?
#Completar

penales_local = mundial.groupby("1")["1_panelties_scored"].sum()
penales_visitante = mundial.groupby("2")["2_panelties_scored"].sum()

penales_anotados = penales_local.add(penales_visitante, fill_value=0)
seleccion_mas_penales = penales_anotados.idxmax()
print(f"{seleccion_mas_penales}: {int(penales_anotados.max())} penales convertidos")

ARGENTINA: 4 penales convertidos

In [34]:
# Cual es la selección que mas penales le hicieron?
# Completar
penales_contra_local = mundial.groupby("1")["2_panelties_scored"].sum()
penales_contra_visitante = mundial.groupby("2")["1_panelties_scored"].sum()

penales_contra = penales_contra_local.add(penales_contra_visitante, fill_value=0)
equipo = penales_contra.idxmax()
print(f"{equipo}: {int(penales_contra.max())} penales en contra")

FRANCE: 3 penales en contra

### Segunda Parte

In [50]:
equipo : str = "ARGENTINA"

In [51]:
# Seleccionar todos los partidos que jugo el equipo de "local"
# Completar

filtroLocal : pd.Series = mundial["1"] == equipo
mundial[filtroLocal]

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361
23,24,Sat,26-Nov-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Group C,ARGENTINA,MEXICO,88966,...,0,0,4,5,0,0,63,79,220,327
49,50,Sat,3-Dec-22,20:00,Ahmed bin Ali Stadium,Szymon Marciniak,Round of 16,ARGENTINA,AUSTRALIA,45032,...,0,0,5,14,1,0,67,73,240,453
60,61,Tue,13-Dec-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Semi-Final,ARGENTINA,CROATIA,88966,...,1,0,12,10,0,0,85,63,321,260
63,64,Sun,18-Dec-22,16:00,Lusail Iconic Stadium,Szymon Marciniak,Final,ARGENTINA,FRANCE,88966,...,1,2,11,21,0,0,87,104,280,409

In [52]:
# Seleccionar todos los partidos que jugo el equipo de "visitante"
# Completar

filtroVisitante : pd.Series = mundial["2"] == equipo
mundial[filtroVisitante]

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
38,39,Wed,30-Nov-22,20:00,Lusail Iconic Stadium,Michael Oliver,Group C,POLAND,ARGENTINA,84985,...,0,0,25,4,0,0,67,48,438,141
57,58,Fri,9-Dec-22,20:00,Lusail Iconic Stadium,Antonio Mateu Lahoz,Quarter-final,NETHERLANDS,ARGENTINA,88235,...,0,1,15,5,0,0,91,79,401,323

In [53]:
# Seleccionar todos los partidos que jugo el equipo (de "local" o "visitante")
partidos : pd.DataFrame = mundial[filtroLocal | filtroVisitante]
partidos

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361
23,24,Sat,26-Nov-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Group C,ARGENTINA,MEXICO,88966,...,0,0,4,5,0,0,63,79,220,327
38,39,Wed,30-Nov-22,20:00,Lusail Iconic Stadium,Michael Oliver,Group C,POLAND,ARGENTINA,84985,...,0,0,25,4,0,0,67,48,438,141
49,50,Sat,3-Dec-22,20:00,Ahmed bin Ali Stadium,Szymon Marciniak,Round of 16,ARGENTINA,AUSTRALIA,45032,...,0,0,5,14,1,0,67,73,240,453
57,58,Fri,9-Dec-22,20:00,Lusail Iconic Stadium,Antonio Mateu Lahoz,Quarter-final,NETHERLANDS,ARGENTINA,88235,...,0,1,15,5,0,0,91,79,401,323
60,61,Tue,13-Dec-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Semi-Final,ARGENTINA,CROATIA,88966,...,1,0,12,10,0,0,85,63,321,260
63,64,Sun,18-Dec-22,16:00,Lusail Iconic Stadium,Szymon Marciniak,Final,ARGENTINA,FRANCE,88966,...,1,2,11,21,0,0,87,104,280,409

In [54]:
# Cuantos goles hizo el equipo en total (obtener los goles metidos de local y sumarlos con los goles metidos de visitante)
goles_local = mundial[filtroLocal]["1_goals"].sum()
goles_visitante = mundial[filtroVisitante]["2_goals"].sum()

goles : int = goles_local + goles_visitante
print(f"{equipo} hizo {goles} goles en total")

ARGENTINA hizo 15 goles en total

In [55]:
# Cuantos goles hizo el equipo en promedio
# Completar
promedio = goles / len(partidos)
print(f"{equipo} hizo {promedio:.2f} goles por partido")

ARGENTINA hizo 2.14 goles por partido

In [56]:
# Cuantos partidos gano el equipo
# Completar
victorias_local = mundial[filtroLocal & (mundial["1_goals"] > mundial["2_goals"])]
victorias_visitante = mundial[filtroVisitante & (mundial["2_goals"] > mundial["1_goals"])]

ganados : int = len(victorias_local) + len(victorias_visitante)
print(f"{equipo} ganó {ganados} partidos")

ARGENTINA ganó 4 partidos

In [ ]:
# Graficar los goles hechos por el equipo en cada partido

fig, ax = plt.subplots()
# Completar

### Tercera Parte

In [ ]:
# Contar cuantos goles hizo cada equipo en total en el mundial
# Completar

equipos = 
goles =

In [ ]:
# Graficar los goles por equipo en todo el mundial

fig, ax = plt.subplots()
# Completar

In [ ]:
# Cual es el equipo que hizo mas goles en el mundial?
# Completar

In [ ]:
# Por cada partido, cual fue la diferencia de goles?
# Completar

In [ ]:
# Por cada partido, cual fue el equipo que gano?
# Completar

In [ ]:
# En cada fase del mundial, cual fue el equipo que hizo mas goles?
# Completar

### Tercera Parte

In [ ]:
# Armar un gráfico a partir de algun nuevo análisis que se te ocurra
# Completar